### ISSUE TITLE
A fail before any task being processed

### ISSUE THREAD

**Issue by reiy-leo** [ranaroussi/multitasking#4]
```python
Traceback (most recent call last):
  File "fixed/insert_journal.py", line 132, in <module>
    get_content(key, _ind)
  File "/usr/local/lib/python3.7/site-packages/multitasking/__init__.py", line 118, in async_method
    single.start()
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 847, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
But after a seconds or several seconds pause, the processing is going on well.

It seems the init stage of multitasking has some errors unhandled

**Comment by ranaroussi** [comment]
Closing for now. Please reopen issue if the problem persists.
